apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: supersecrets.operators.on.hands
spec:
  group: operators.on.hands
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: SuperSecret
    listKind: SuperSecretList
    plural: supersecrets
    singular: supersecret
    shortNames:
      - ss
  validation:
    openAPIV3Schema:
      type: object
      properties:
        encryptedSecretValue:
          type: string
