---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: killpod-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: killpod-operator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: killpod-operator
  namespace: default
roleRef:
  kind: Role
  name: killpod-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: killpod-operator
    namespace: default
