apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: microservices.operators.on.hands
spec:
  group: operators.on.hands
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: Microservice
    listKind: MicroserviceList
    plural: microservices
    singular: microservice
    shortNames:
      - ss
  validation:
    openAPIV3Schema:
      type: object
      properties:
        replicas:
          type: integer
        image:
          type: string
        labels:
          type: object
